services:
  app1: &app
    image: ricardo2010/payment-app:v2
    container_name: app1
    networks:
      - payment-processor
    environment:
      - MIX_ENV=prod
      - RELEASE_COOKIE=secret_cookie
      - RELEASE_NODE=api1@app1
      - PEER_NODES=api2@app2
      - ERL_MAX_PORTS=2046
      - PORT=9999
      - ELIXIR_ERL_OPTIONS=+S 1:1 +A 2 +sbwt none +sbwtdcpu none +sbwtdio none
      - SECRET_KEY_BASE=j/s16IqcuOkGYYwGZBPTZc9clvsn7ZDeg3w+/EGAHUzDZa+VxEma/TGKMXfLXIZ2
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    healthcheck:
      test: curl -f http://app1:9999/health
      interval: 15s
      timeout: 15s
      start_period: 30s
      start_interval: 1s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "150M"

  app2:
    <<: *app
    container_name: app2
    environment:
      - MIX_ENV=prod
      - RELEASE_COOKIE=secret_cookie
      - RELEASE_NODE=api2@app2
      - PEER_NODES=api1@app1
      - ERL_MAX_PORTS=2046
      - PORT=9999
      - ELIXIR_ERL_OPTIONS=+S 1:1 +A 2 +sbwt none +sbwtdcpu none +sbwtdio none
      - SECRET_KEY_BASE=j/s16IqcuOkGYYwGZBPTZc9clvsn7ZDeg3w+/EGAHUzDZa+VxEma/TGKMXfLXIZ2
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    healthcheck:
      test: curl -f http://app2:9999/health
      interval: 15s
      timeout: 15s
      start_period: 30s
      start_interval: 1s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "150M"

  nginx:
    image: nginx:1.29.0-alpine 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - app1
      - app2
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '50MB'

networks:
  payment-processor:
    external: true
